# 使用官方 Node.js 镜像作为基础镜像
FROM node:20.15.1

# 设置工作目录
WORKDIR /

# 复制 package.json 和 package-lock.json 并安装依赖
COPY package*.json ./
RUN npm install

# 复制所有文件到工作目录
COPY . .

# 复制 Angular 构建后的文件到 NestJS 的静态文件目录
# 构建 NestJS 应用
RUN npm run build

# 暴露 NestJS 默认的端口
EXPOSE 3000

# 启动 NestJS 应用
CMD ["npm", "run", "start:prod"]
